In [5]:
import numpy as np
import glob
import matplotlib

In [46]:
files = glob.glob('detection_files/*.txt')



In [8]:
files

['detection_files\\FRCNN_det.txt',
 'detection_files\\HeadHunter-DPM_det.txt',
 'detection_files\\PVA_det.txt',
 'detection_files\\RFCN-101_det.txt',
 'detection_files\\RFCN-50_det.txt',
 'detection_files\\SSD_det.txt',
 'detection_files\\Viola-Jones_det.txt']

In [68]:
seuil = [0.1, 0.5, 0.7]

In [87]:
TP = np.zeros((len(files),len(seuil)))
TN = np.zeros((len(files),len(seuil)))
FP = np.zeros((len(files),len(seuil)))
FN = np.zeros((len(files),len(seuil)))
Recall = np.zeros((len(files),len(seuil)))
FPR = np.zeros((len(files),len(seuil)))

for m in range (len(files)):
    data = np.loadtxt(files[m])
    for n in range (len(seuil)):
        
        for i in range (len(data)):
            if (data[i][0]>=seuil[n]) & (data[i][1] == 1):
                TP[m][n] = TP[m][n] + 1
            elif (data[i][0]<seuil[n]) & (data[i][1] == 0):
                TN[m][n] = TN[m][n] + 1
            elif (data[i][0]<seuil[n]) & (data[i][1] == 1):
                FN[m][n] = FN[m][n] + 1
            else:
                FP[m][n] = FP[m][n] + 1

        Recall[m][n] = (TP[m][n])/(TP[m][n]+FN[m][n])
        FPR[m][n] = (FP[m][n])/(FP[m][n]+TN[m][n])

In [88]:
FN

array([[ 358.,  375.,  383.],
       [1129., 1129., 1307.],
       [ 394.,  434.,  473.],
       [ 364.,  402.,  418.],
       [ 343.,  381.,  396.],
       [ 549., 1036., 1267.],
       [1628., 2213., 3484.]])

In [89]:
Recall

array([[0.93076774, 0.92748018, 0.92593309],
       [0.78166699, 0.78166699, 0.74724425],
       [0.92380584, 0.91607039, 0.90852833],
       [0.92960743, 0.92225875, 0.91916457],
       [0.93366854, 0.92631986, 0.92341907],
       [0.89383098, 0.7996519 , 0.75497969],
       [0.68516728, 0.57203636, 0.32624251]])

In [90]:
FPR

array([[1.        , 0.59746328, 0.49599466],
       [1.        , 1.        , 0.28732394],
       [1.        , 0.47172012, 0.32536443],
       [1.        , 0.61653272, 0.50057405],
       [1.        , 0.55121951, 0.46707317],
       [1.        , 0.01723942, 0.00910332],
       [0.96920583, 0.24959481, 0.04538088]])

In [91]:
column_sums = TN.sum(axis=0)

In [92]:
column_sums

array([1.9000e+01, 1.9947e+04, 2.1042e+04])